= Relational Baggage

"Throw off anything that hinders and the sin that so easily entangles.” Hebrews 12:1

== Notes

* Most of us are probably heading in the right direction, but because of the baggage that we are carrying with us, we are not enjoying the journey very much.
* Many people just adjust to the luggage they pick up along the way, but much of it really is not supposed to be part of the trip.
* Physical wounds vs emotional wounds. Lots of different broken things in life can leave very deep wounds in the heart.
* Story of Terah (father of Abraham, Nahor, *Haran*). _Gen 11: 27-28_
** Terah leaves for Canaan (modern day Israel, the promised land) _Gen 11: 29 - 31_
** Terah settles in Haran, not completing his journey. _Get 11: 31 - 32_
* Sometimes we make poor decisions based on/afraid of the wounds we carry and it defines our lives.
** Such wounds keep us from our *potential*. (_Psalm 73: 21 - 22_ pain clouds our judgement) *The pain is not really about you and your problem (e.g. bad marriage, abusive dad, etc.) - its the enemy trying to derail you form you purpose.*
** *Pollutes* our other relationships. (_Heb 12: 15_)
** It makes us *defensive*. We start putting walls around ourselves and defend even against the people who can really help us.
** Makes us *distant*. E.g. "I'm going to get hurt if this keeps on going."
** Makes us *demanding*. Insecure people try to grab for control of everything.
** *Hurts* our relationship with God. (Hard to love, hard to forgive and/or ask for forgiveness.)
* You can't go through life hating people and still have a good relationship with God. _Mark 11: 25_ ("**First** forgive, *then* father will forgive you.")
* Jesus even couldn't summarise it down to one law, He gave us two: "1. - Love God. 2. - Love people."
* Lords prayer is a "dangerous" one. ("Frogive us *as* we forgive.") _Matthew 6: 12 - 14_
* You have to settle the "horisontal" if you want the "vertical" to work well (in fact, everything else to work well).
* _Psa 147:3_ (God heals the brokenhearted)
* To brake some strongholds in your life, you need to change some thoughts. And that can be really difficult.
* Consider - Is your way working?
* You can go through by:
** *Revealing* your hurt to somebody. _Psalm 32: 3 ; 39: 2_
** *Release* the people involved, even if they don't deserve it. (The more you hold it against them, the more you are going to become like them.) _Mat 18: 21 - 22_ (forgive 70*7 times.)
** *Refocus* on God's plan for your life.
* _1 Peter 2: 23_ (When they hurt thim, He forgave, and entrusted Himself to God who judges justly.) ; Allso Joseph in Genesis 50, didn't get back at his brothers, but praised God.
* Job 11: 13 - 16 (Put your heart right, reach out to God... and then face the world again firm and courageous.)
